### ISSUE TITLE
DPDK Build Issue

### ISSUE THREAD

**Issue by ertza** [sands-lab/omnireduce#2]
Hi, I have been trying to follow the guide and install by running 
`./build_all.sh MLX5 CONDA INSTALL NOSCALING SKIP_EXPS SKIP_EXAMPLES PYTORCH`, 
but run into the following issue at the DPDK build step:

> == Build buildtools
> == Build kernel
> == Build kernel/linux
> == Build buildtools/pmdinfogen
> == Build kernel/linux/igb_uio
> == Build kernel/linux/kni
>   HOSTCC pmdinfogen.o
>   HOSTLD dpdk-pmdinfogen
>   INSTALL-HOSTAPP dpdk-pmdinfogen
> == Build drivers
> make[5]: *** /lib/modules/5.6.13-0_fbk17_zion_5815_gc01d8dbd2635/build: No such file or directory.  Stop.
> make[4]: *** [/root/tmp/omnireduce/omnireduce-DPDK/daiet/lib/dpdk/mk/rte.module.mk:51: rte_kni.ko] Error 2
> make[3]: *** [/root/tmp/omnireduce/omnireduce-DPDK/daiet/lib/dpdk/mk/rte.subdir.mk:37: kni] Error 2
> make[3]: *** Waiting for unfinished jobs....
> make[5]: *** /lib/modules/5.6.13-0_fbk17_zion_5815_gc01d8dbd2635/build: No such file or directory.  Stop.
> make[4]: *** [/root/tmp/omnireduce/omnireduce-DPDK/daiet/lib/dpdk/mk/rte.module.mk:51: igb_uio.ko] Error 2
> make[3]: *** [/root/tmp/omnireduce/omnireduce-DPDK/daiet/lib/dpdk/mk/rte.subdir.mk:37: igb_uio] Error 2
> make[2]: *** [/root/tmp/omnireduce/omnireduce-DPDK/daiet/lib/dpdk/mk/rte.subdir.mk:37: linux] Error 2
> make[1]: *** [/root/tmp/omnireduce/omnireduce-DPDK/daiet/lib/dpdk/mk/rte.sdkbuild.mk:48: kernel] Error 2
> make[1]: *** Waiting for unfinished jobs....

I am running it in docker in the following env:
> OS: "CentOS Linux 8"
> Arch: "Intel Corporation Sky Lake"
> Ethernet controller: "Mellanox Technologies MT2892 Family [ConnectX-6 Dx]"

Also, I have installed the latest DPDK separately and it gets compiled correctly, but for this OmniReduce version it fails. Any pointers in this regard to compile this, or correctly point OmniReduce to the installation of latest DPDK would be really helpful. Although the newer DPDK versions usually don't work with applications using older APIs, which I think would be the case here.

**Comment by ertza** [comment]
I can go forward by adding a `SKIP_DPDK`, but then it fails at building PyTorch and says it cannot find Gloo.

> AT_INSTALL_INCLUDE_DIR include/ATen/core
> core header install: /root/tmp/omnireduce/omnireduce-DPDK/pytorch/build/aten/src/ATen/core/TensorBody.h
> -- /usr/bin/c++ /root/tmp/omnireduce/omnireduce-DPDK/pytorch/torch/abi-check.cpp -o /root/tmp/omnireduce/omnireduce-DPDK/pytorch/build/abi-check
> -- Determined _GLIBCXX_USE_CXX11_ABI=1
> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>   Could NOT find Gloo (missing: Gloo_INCLUDE_DIR Gloo_LIBRARY)
> Call Stack (most recent call first):
>   /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>   cmake/Modules/FindGloo.cmake:44 (find_package_handle_standard_args)
>   torch/lib/c10d/CMakeLists.txt:76 (find_package)

Although Gloo builds and installs correctly before this
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /root/tmp/omnireduce/omnireduce-DPDK/gloo/build
> + make install
> Consolidate compiler generated dependencies of target gloo
> [100%] Built target gloo
> Install the project...

**Comment by ChenYuHo** [comment]
Are you building DPDK inside docker container?
We install DPDK in the host machine and didn't see this problem before.
Your NIC supports RoCE so you may try the RDMA version instead.

**Comment by ertza** [comment]
Yes I am building inside the docker. That should not be the issue here as the newer DPDK version does compile fine, might be some incompatibility with the newer OS or arch. But anyways even skipping the DPDK, how to solve the Gloo issue?

For my particular use-case, I need to run PyTorch/Gloo/DAIET/DPDK so have to make this one work. Right now the only blocking issue is that pytorch make cannot fine Gloo `Could NOT find Gloo (missing: Gloo_INCLUDE_DIR Gloo_LIBRARY)`

**Comment by ChenYuHo** [comment]
If you were following the doc, you should have a conda environment. Check if you do have gloo installed in your `${CONDA_PREFIX}`
If yes, try passing `Gloo_INCLUDE_DIR=${CONDA_PREFIX}/include` and `Gloo_LIBRARY=${CONDA_PREFIX}/lib` when building PyTorch as the error message says those are missing.

**Comment by ertza** [comment]
Fixed! I wasn't sure what to pass as the paths for include and lib directories, this worked.
