### ISSUE TITLE
Fail to run OmniReduce-RDMA example

### ISSUE THREAD

**Issue by VoidStardust** [sands-lab/omnireduce#5]
### Description:

Hello,
I encountered an error message "ibv_reg_mr cuda_comm_buf failed with mr_flags=7" while running OmniReduce-RDMA example. I'm trying to run the single node example which the aggregator and the worker are on the same machine.

### Steps to reproduce:

1. Compile as README said.
2. Modify the `.cfg` file

```
[omnireduce]
num_workers = 1
num_aggregators = 1
num_threads = 8
worker_cores = -1,-1,-1,-1,-1,-1,-1,-1
aggregator_cores = -1,-1,-1,-1,-1,-1,-1,-1
threshold = 0.0
buffer_size = 1024
chunk_size = 1048576
bitmap_chunk_size = 16777216
message_size = 256
block_size = 256
ib_hca = mlx5_0
ib_port = 1
gid_idx = 2
sl = 2
gpu_devId = 0
direct_memory = 1
adaptive_blocksize = 0
tcp_port = 19875
worker_ips = 127.0.0.1
aggregator_ips = 127.0.0.1

```

3. Run aggregators

``` bash
$ ./aggregator 
IB device: mlx5_0
```

4. Run workers, and observe the error message "ibv_reg_mr cuda_comm_buf failed with mr_flags=7" as below

``` bash
$ mpirun -n 1 -host 127.0.0.1 ./cuda_worker
CUDA device [NVIDIA A100-PCIE-40GB]
IB device: mlx5_0
ibv_reg_mr cuda_comm_buf failed with mr_flags=7
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[19406,1],0]
  Exit code:    1
--------------------------------------------------------------------------
```

### Expected behavior:

The program should run without any errors and show the calculated `algbw`.

### Actual behavior:

The error message "ibv_reg_mr cuda_comm_buf failed with mr_flags=7" is displayed, and the cuda_worker fails to run.

### Additional information:
I'm not sure what the "mr_flags=7" part of the error message means, or how to fix the problem. I've tried searching online for solutions, but haven't found anything that helps. Any suggestions or advice would be greatly appreciated.

Thank you for your help!

Alex Li

**Comment by Tonny-Gu** [comment]
Hello. I suggest reading [this article](https://nekodaemon.com/2023/03/29/How-to-properly-setup-GPUDirect-RDMA/) first, then try with ibv_write_bw to check the environment.

**Comment by VoidStardust** [comment]
Hello,

I wanted to follow up and share that I was able to identify the issue with the program. It turns out that the problem was with the gdr driver. When I set `direct_memory = 0`, the example worked fine.

In my case, the nvidia driver already included the gdr driver, and all I needed to do was load it using the command:

``` bash
# modprobe nvidia-peermem
```

After doing this, everything worked well.

Thank you for your help and support!

**Comment by ChenYuHo** [comment]
Glad that you resolved the issue!
